### ISSUE TITLE
Query Devices instructions unclear

### ISSUE THREAD

**Issue by FreeWilly2022** [mainsail-crew/gb-docs#15]
Thank you for adding the query devices feature, I found it very helpful after doing a major re-wire to confirm everything is connected. I just want to make you aware that the explanation in the features overview is missing key information, specifically where this tab appears.
 I found it in a post on-line, but it would be helpful to have it in the official documentation. I think that it would be helpful to add the following sentence to the top of the features/query-devices.md file:

Mainsail can list different CAN / Serial / USB / Video devices to find the right hardware path for your config. Open any file in the Mainsail editor (from the upper left of the window, select Machine from the pull down, and in the Config Files window open any file), and a Devices tab will be available at the top.

References:
https://github.com/mainsail-crew/gb-docs/blob/main/overview/features/query-devices.md

https://www.teamfdm.com/forums/topic/2705-mainsailklipper-device-feature/

**Comment by meteyou** [comment]
Thanks for your feedback! I added a second line to the first paragraph. unfortunately, the length of the text is limited here in the docs, as this paragraph is also used for SEO. if this is not enough, i would add another headline with detailed text.

![image](https://github.com/mainsail-crew/gb-docs/assets/8167632/88271724-b3b9-4864-a6e2-948c1c74bb42)
