### ISSUE TITLE
Typo: "Build-in themes" should be "Built-in themes"

### ISSUE THREAD

**Issue by prplwtf** [mainsail-crew/gb-docs#18]
Compare the [definition of build-in](https://www.oxfordlearnersdictionaries.com/definition/english/build-in) to the [definition of built-in](https://www.oxfordlearnersdictionaries.com/definition/english/built-in).

File in question: https://github.com/mainsail-crew/gb-docs/blob/main/overview/features/build-in-themes.md \
Website URL: https://docs.mainsail.xyz/overview/features/build-in-themes

**Comment by prplwtf** [comment]
Don't feel comfortable proposing a pull-request on this one. Renaming the file itself could result into broken links.

**Comment by meteyou** [comment]
Thx for this "typo report" (bug report sounds wrong here). I fixed it via gitbooks webinterface, so I wasnt able to link this issue in the PR. Here is the commit of the fix: https://github.com/mainsail-crew/gb-docs/commit/9ae39fe4ec98f697e87015e894abc704ebb3ffeb

**Comment by prplwtf** [comment]
Glad to help!
